In [1]:
import numpy as np

In [2]:
# creating arrays

my_list = [1, 2, 3]
n = np.array(my_list)
n

array([1, 2, 3])

In [3]:
m = np.array([4, 5, 6])
m

array([4, 5, 6])

In [7]:
# mulit-dimensional array, is a matrice or list of lists

x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x.shape # gives the dimension of the array as (rows, columns)

(2, 3)

In [12]:
r = np.arange(0, 20, 2) # gives a range of numbers from starting point, ending point, with step
r

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
r = r.reshape(5, 2) # reshapes the array into the rows and columns
r

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [18]:
o = np.linspace(0, 5, 9) # automatically generates numbers from starting to end point with n numbers
o

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [23]:
o.resize(3,3) # resizes the array into given dimensions
o

array([[0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

In [38]:
identity = np.eye(3) # identity matrix of size 3
identity

one = np.ones([2,1], int) # one matrix
one

diag = np.diag([1,2,3,4,5]) # diagonal matrix of size of the list passed
diag

zero = np.zeros(3) # zero array of size 3
zero

rep1 = np.repeat(m, 2) # creating array with repeating values
rep1

rep2 = np.array([1, 2, 3] * 3) # creating array with repeating values by multiplication
rep2

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [47]:
p = np.ones([2,3], int)

vp = np.vstack([p, p*3]) # stacking the matrix vertically
vp

hp = np.hstack([p, p*2]) # stacking the matrix horizontally
hp

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [48]:
m + n # simple addition

array([5, 7, 9])

In [50]:
m.dot(3) # scalar dot product

m.dot(n) # matrix dot product

32

In [51]:
z = np.array([m, m**2]) # squarred of the array
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [52]:
zt = z.T # transpose of the matrix
zt

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [53]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [54]:
s.max() # min element

144

In [55]:
s.min() # max element

0

In [56]:
s.argmax() # index of max element

12

In [57]:
s.argmin() # index of min element

0

In [58]:
s.sum() # sum of array

650

In [59]:
s.mean() # mean of array

50.0

In [60]:
s.std() # standard deviation of array

46.58325879540846

In [61]:
b = np.arange(36)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [63]:
b.resize(6,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
b[1] # gets the row at index 1

array([ 6,  7,  8,  9, 10, 11])

In [65]:
b[1][3] # element at row at index 1 and column at index 3

9

In [66]:
b[b > 30] # gets all elements greater than 30 

array([31, 32, 33, 34, 35])

In [68]:
b[b > 30] = 30 # if elements greater than 30, assign value 30 to them
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [69]:
test = np.random.randint(0, 10, (3, 4)) # create random array
test

array([[2, 8, 5, 8],
       [8, 6, 5, 5],
       [7, 0, 2, 1]])

In [70]:
# simple iteration
for i in test:
    print(i)

[2 8 5 8]
[8 6 5 5]
[7 0 2 1]


In [72]:
# iteration using range and indexing
for i in range(len(test)):
    print('row', i, 'is',test[i])

row 0 is [2 8 5 8]
row 1 is [8 6 5 5]
row 2 is [7 0 2 1]


In [73]:
# iteration using enumerate
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [2 8 5 8]
row 1 is [8 6 5 5]
row 2 is [7 0 2 1]


In [74]:
test2 = test**2
test2

array([[ 4, 64, 25, 64],
       [64, 36, 25, 25],
       [49,  0,  4,  1]], dtype=int32)

In [75]:
# iterating over 2 arrays
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[2 8 5 8] + [ 4 64 25 64] = [ 6 72 30 72]
[8 6 5 5] + [64 36 25 25] = [72 42 30 30]
[7 0 2 1] + [49  0  4  1] = [56  0  6  2]
